### ISSUE TITLE
Conflict issue with Molongui Authorship plugin in 2.0.56 versio

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#609] opened 2023-10-13 08:16 UTC
Ref tickets:- https://magazine3.in/conversation/200777?folder_id=21

Description:-
When user update to latest version Swedish/Scandinavian (Swedish, Finnish, Norwegian and Danish) character changed.

Here is the screenshot:-
https://prnt.sc/h7SOjkKcRdX8 (in version 2.0.55)
https://prnt.sc/ohLh92-8xEVm (in version 2.0.56)

**Comment by MohammedAkramU7** [comment] 2023-10-13 08:16
Another user:- https://magazine3.in/conversation/199921?folder_id=21

**Comment by Sanjeevsetu** [comment] 2023-10-13 10:18
Duplicate of ticket no. https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/608.

**Closed** 2023-10-13 10:19 UTC
