### ISSUE TITLE
Upgrade to 2.0.51 kills Simple:Press Forum

### ISSUE THREAD

**Issue by MikeAlderan** [ahmedkaludi/Easy-Table-of-Contents#518] opened 2023-07-04 21:53 UTC
Upgrade to 2.0.51 makes the Simple:Press Forum completely unusable, pages and forum-content  is "distorted" and "missaligned".

No problems with 2.0.50 and never ever with any version before. Something must be introdruced with 2.0.51 that causes this effect.

Rollback to 2.0.50 fixes the problem immediately, so the cause is Easy-Table-of-Content.

**Comment by Sanjeevsetu** [comment] 2023-07-05 06:44
Hi @MikeAlderan 

Could you please help us to find the cause. share the urls with issues on it or contact our support.

**Comment by Sanjeevsetu** [comment] 2023-07-05 14:26
Hi @MikeAlderan 

We have just released a patch. Kindly update to our latest v 2.0.51.1 and let us know..

Thank you so much.

**Comment by MikeAlderan** [comment] 2023-07-05 21:48
Sorry for the late reaction, this is not my main task.

But you obviously nailed it without any further feedback. Whatever it was, it is gone with 2.0.51.1

Thanks!

**Comment by Sanjeevsetu** [comment] 2023-07-07 07:26
Hi @MikeAlderan 

Nice to hear that. I am closing this ticket. If you need any further assistance, Please create new ticket orcontact us.

**Closed by Sanjeevsetu** 2023-07-07 07:26 UTC
