### ISSUE TITLE
Need to add "Change Header Label" option for specific post/page.

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/Easy-Table-of-Contents#371] opened 2022-12-22 06:35 UTC
There is a need to add "Change Header Label" option for specific post/page so that users can put different Header for different posts.

Reference ticket -: https://magazine3.in/conversation/83225?folder_id=23

**Comment by Sanjeevsetu** [comment] 2023-11-29 16:59
This is duplicate of https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/472

**Closed by Sanjeevsetu** 2023-11-29 16:59 UTC
Labels: enhancement, P:High, feature
