### ISSUE TITLE
Visitors are unable to scroll to the bottom of the page

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/Easy-Table-of-Contents#561] opened 2023-08-14 09:35 UTC
On the user end, the visitors are unable to scroll to the bottom of the page

Ref ticket: https://magazine3.in/conversation/170417?folder_id=27

**Comment by akshaywali** [comment] 2023-08-29 12:20
It is confirmed from the user that scroll issue was due to the theme . So  Closing this ticket.

**Closed by akshaywali** 2023-08-29 12:20 UTC
Labels: bug, P:High
