### ISSUE TITLE
Warning appears with compatibility function

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#595] opened 2023-09-25 08:50 UTC
Ref ticket:-https://magazine3.in/conversation/190656?folder_id=21

Description:-
When the user activates the plugin, a warning appears, and it's an issue with the compatibility code.

Here is the screenshots
https://prnt.sc/MOnU071cejTL
https://prnt.sc/XUhfow1fRkwv
https://prnt.sc/0RkdMRaB3BXm ( code which create a issue)

**Comment by Rkroy** [comment] 2023-10-13 11:13
https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/606

**Comment by Sanjeevsetu** [comment] 2023-10-13 13:12
This ticket is duplicate of ticket no. https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/606. so I am closing it

**Closed by Sanjeevsetu** 2023-10-13 13:12 UTC
Labels: bug, Ready for Review, P:High
