### ISSUE TITLE
Option to hide Easy Toc from posts of a specific category.

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/Easy-Table-of-Contents#354] opened 2022-12-07 10:26 UTC
Reference ticket: https://wordpress.org/support/topic/exclude-easy-toc-from-posts-by-category-wordpress/

**Comment by MohammedAkramU7** [comment] 2023-02-01 13:20
Another user: https://magazine3.in/conversation/99661?folder_id=21

**Comment by Sasirekhamarella** [comment] 2023-03-27 12:11
Another user: https://wordpress.org/support/topic/exclude-url-9/

**Comment by Sanjeevsetu** [comment] 2023-12-13 18:00
Duplicate of https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/631

**Closed by Sanjeevsetu** 2023-12-13 18:00 UTC
Labels: enhancement
