### ISSUE TITLE
doesn't work with Elementor Templates and the Post Content widget

### ISSUE THREAD

**Issue by Ping123** [ahmedkaludi/Easy-Table-of-Contents#250] opened 2022-08-08 12:46 UTC
The plug-in does not work properly when using the “Post Content” widget in an Elementor template.
If I create a post which uses a Elementor Template and insert the plugin (for example via shortcode), I get a table of contents, but the anchors are not added to the DOM.

### Steps to reproduce:

- Create a template for single posts in Elementor
- add the Post-Content widget to the template
- Create a post that uses the template and has content
- add the table of contents plug-in to the post

### Isolating the problem

- This bug happens with only Elementor, Elementor Pro and Easy Table of Contents plugin active.
- This bug happens with a Blank WordPress theme active (Hello theme).
- I can reproduce this bug consistently using the steps above.

**Comment by Zabi09** [comment] 2022-08-25 09:19
I have added the shortcode inside the elementor and the shortcode is working fine I have also tried adding the same shortcode with some of the other widgets and that is also working fine - https://prnt.sc/PSBeOo-DvUU6

Will you please create a small video or explain to us step by step to recreate the issue you are facing so that we can check the same and come up with a solution

Please let us know

**Comment by Ping123** [comment] 2022-08-25 09:55
Thanks for the Reply!
Here is a Video that might be explain better what i mean.

https://user-images.githubusercontent.com/9369322/186634730-3bc091e9-497b-4c2b-a5fc-b99aed7d1fe9.mp4

**Comment by muslimakhan** [comment] 2022-09-05 14:00
@Ping123 Sir provide us more details about settings of Easy Table of Contents, please check below:

1. You have to check from ETOC settings, where you should be enabled the post type for Single Posting of Elements. Please check this image:
![Table-of-Contents-‹-My-Site-—-WordPress (6)](https://user-images.githubusercontent.com/12198305/188466173-4766e563-e90b-4ce7-b33d-68f8e3069059.png)

2. Create an issue on support and send us credentials for admin so we will check and let you know further steps:
https://wordpress.org/support/plugin/easy-table-of-contents/

**Comment by Ping123** [comment] 2022-09-05 14:45
Hello @muslimakhan 

Here are my settings in the backend of ez-toc
![settings](https://user-images.githubusercontent.com/9369322/188474266-83765848-5598-46f4-98d1-a47ff6fd5ae2.png)
For testing purposes, I have everything enabled.

You don't need my admin access as it occurs on any website.
To replicate the behavior I refer you to my video which is basically a step-by-step guide.

Maybe this Elementor Hook could help you to solve the problem:
```
function restrict_content_check( $content ) {

	if ( ! membership_plugin_is_content_allowed() ) {
		$content = esc_html__( 'Forbidden', 'plugin-name' );
		return;
	}

	return $content;

}
add_action( 'elementor/frontend/the_content', 'restrict_content_check' );
```
https://developers.elementor.com/docs/hooks/frontend-content/

**Comment by muslimakhan** [comment] 2022-09-06 05:36
Hello @Ping123 sir,

Thanks for sharing with us your setting details & hint for solving this problem from code level, let us add this action on our plugin, and after we will share with you a link for downloading the updated plugin code, please check once at your end and let us know it will be clear the bug or not.

Thanks

**Comment by muslimakhan** [comment] 2022-09-06 08:04
Hey @Ping123 Sir, 
Please check this above commit and add these changes line into your Easy Table of Contents Plugin and let me know if it is removed bug or not?
Or
If you want Easy Table of Contents Plugin zip file for upload plugin then tell me?

Thanks 
@muslimakhan

**Comment by Ping123** [comment] 2022-09-06 10:14
Hey @muslimakhan 

I have tried your code, but unfortunately it is incomplete
so I have adjusted the code a little bit, now it works.

Here is what I did:
in the -> easy-table-of-contents/easy-table-of-contents.php
```
/**
 * Add the core action filter hook.
 *
 * @access private
 * @since  1.0
 * @static
 */

private static function hooks() {

    //add_action( 'plugins_loaded', array( __CLASS__, 'loadTextdomain' ) );
    add_action('wp_enqueue_scripts', array(__CLASS__, 'enqueueScripts'));
    add_action('admin_head', array(__CLASS__, 'addEditorButton'));
    
    // Run after shortcodes are interpreted (priority 10).
    if (in_array('elementor/elementor.php', apply_filters('active_plugins', get_option('active_plugins')))) {
        add_filter('elementor/frontend/the_content', array(__CLASS__, 'the_content'), 100);
    } else {
        add_filter('the_content', array(__CLASS__, 'the_content'), 100);
    }

    add_shortcode('ez-toc', array(__CLASS__, 'shortcode'));
    add_shortcode('lwptoc', array(__CLASS__, 'shortcode'));
    add_shortcode(apply_filters('ez_toc_shortcode', 'toc'), array(__CLASS__, 'shortcode'));
}
```

in the -> easy-table-of-contents/includes/class.post.php
```
/**
 * Apply `the_content` filter to the post content.
 *
 * @since  2.0
 *
 * @return static
 */
private function applyContentFilter() {

    add_filter( 'strip_shortcodes_tagnames', array( __CLASS__, 'stripShortcodes' ), 10, 2 );

    /*
     * Ensure the ezTOC content filter is not applied when running `the_content` filter.
     */

    if(in_array('elementor/elementor.php', apply_filters('active_plugins', get_option('active_plugins')))){
        remove_filter( 'elementor/frontend/the_content', array( 'ezTOC', 'the_content' ), 100 );
        $this->post->post_content = apply_filters( 'elementor/frontend/the_content', strip_shortcodes( $this->post->post_content ) );
        add_filter( 'elementor/frontend/the_content', array( 'ezTOC', 'the_content' ), 100 );
    } else {
        remove_filter( 'the_content', array( 'ezTOC', 'the_content' ), 100 );
        $this->post->post_content = apply_filters( 'the_content', strip_shortcodes( $this->post->post_content ) );
        add_filter( 'the_content', array( 'ezTOC', 'the_content' ), 100 ); 
    }
    
    remove_filter( 'strip_shortcodes_tagnames', array( __CLASS__, 'stripShortcodes' ) );

    return $this;
}
```

I hope this helps you a little. 
With kind regards

**Comment by muslimakhan** [comment] 2022-09-06 12:36
Hey @Ping123 sir,

We appreciate your efforts to giving us the best solution for this issue, but we will not update this code until we will check in our end, the problem is we have not Elementor license key so we can't check this code in our end sir, so it will be great if you will create a staging server for testing this code, you can join us on below support link and send us staging server credentials there:
https://tocwp.com/contact/

Thanks, with most heartly regards.
@muslimakhan

**Comment by muslimakhan** [comment] 2022-11-30 12:37
Hey @Ping123 sir,

We waited so much time for your reply, but now we have to close this ticket. 
Thanks for us give above solution on it but we can't proceed until we can create issue on our end or check on your server live test.

Thanks
With kind regards

**Closed by muslimakhan** 2022-11-30 12:37 UTC
Labels: bug, Need More Data
