### ISSUE TITLE
The content on my pages is hidden after today's update

### ISSUE THREAD

**Issue by Shaggy1222** [ahmedkaludi/Easy-Table-of-Contents#517] opened 2023-07-04 20:03 UTC
I had to disable the plugin, because is making the posts on my pages disappear.

**Comment by Sanjeevsetu** [comment] 2023-07-05 06:45
Hi @Shaggy1222 

Could you please help us to find the cause. share the urls with issues on it or contact our support.

**Comment by Shaggy1222** [comment] 2023-07-05 06:56
Hi,Now I activate it again for a few hours.Here are some pages: https://histotravel.com/north-america/ https://histotravel.com/south-atlantic-region/https://histotravel.com/virginia/

My website is only at the beginning, I only have 3 posts. The posts are working great with your plugin. The problem appear only at the pages. And I even disable the table from the pages, and it's still making problems.



   On Wednesday, July 5, 2023 at 09:45:37 AM GMT+3, Sanjeev Kumar ***@***.***> wrote:  
 
 


Hi @Shaggy1222

Could you please help us to find the cause. share the urls with issues on it or contact our support.

**Comment by Sanjeevsetu** [comment] 2023-07-05 07:23
Hi @Shaggy1222 

Yeah I can see the issue at your urls. Could you please contact us via https://tocwp.com/contact/.?

**Comment by nodeomega** [comment] 2023-07-05 10:59
Can confirm. I had the same empty content issue at div.content in my post and pages. Had to deactivate to get my site content to load again. Issue did not appear in the Edit Post page, however, as I could see the post contents there.

Site is [https://phoenixiaastrology.com](https://phoenixiaastrology.com). I'm keeping the plugin disabled until this is resolved..

**Comment by Sanjeevsetu** [comment] 2023-07-05 14:28
Hi @nodeomega & @Shaggy1222

We have just released a patch. Kindly update to our latest v 2.0.51.1 and let us know.. I hope this release would fix your issue. 

Thank you so much.

**Comment by Shaggy1222** [comment] 2023-07-05 15:42
Now it works fine after this update. Thanks :)
    On Wednesday, July 5, 2023 at 05:28:47 PM GMT+3, Sanjeev Kumar ***@***.***> wrote:  
 
 


Hi @nodeomega & @Shaggy1222

We have just released a patch. Kindly update to our latest v 2.0.51.1 and let us know.. I hope this release would fix your issue.

Thank you so much.

**Comment by Sanjeevsetu** [comment] 2023-07-05 18:09
Thank you so much @Shaggy1222 for the patience. It feels good to hear that.

**Comment by nodeomega** [comment] 2023-07-05 22:25
Confirmed. It's working now. Thank you very much!

**Comment by Sanjeevsetu** [comment] 2023-07-07 08:22
Thanks @nodeomega and @Shaggy1222 for confirming the same. I am closing this ticket.

**Closed by Sanjeevsetu** 2023-07-07 08:22 UTC
