### ISSUE TITLE
Warning appears in 2.0.58 version

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/Easy-Table-of-Contents#635] opened 2023-11-17 13:19 UTC
Ref ticket:- https://magazine3.in/conversation/213959?folder_id=21

Description:-
After updating to 2.0.58, a warning appears in the frontend posts.

Warning
Warning: Undefined variable $label_below_html in /home/Lit/web/public_html/wp-content/plugins/easy-table-of-contents/includes/class.post.php on line 1458

**Comment by Sanjeevsetu** [comment] 2023-11-21 17:48
This is duplicate of the ticket https://github.com/ahmedkaludi/Easy-Table-of-Contents/issues/636. I am closing it

**Closed by Sanjeevsetu** 2023-11-21 17:48 UTC
